version: 1
builder:
  configs:
    - documentation_targets:
        - Lifetime
        - LifetimePrimitives
        - LifetimeBoundaries
        - LifetimePolicies
        - LifetimeIntent
        - LifetimeResources
        - LifetimeSwiftUI
